project:
  type: website
  output-dir: docs

website:
  title: "Scott Laing, Finance"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - teaching.qmd
      - research.qmd
      - href: CV_Summer23.pdf
        text: CV
      - href: https://youtube.com/@scottlaingfinance
        text: YouTube

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

