---
title: "Research"
editor: visual
---

## Topics of Interest:

Sustainability, Environmental Social Governance (ESG), "Green" Finance, Asset Pricing in the Cross Section of Stock Returns, Corporate Finance, Textual Analysis (NLP Processing), Impact Investing\

### Dissertation: 3 Essays on ESG/Sustainability

*Advisor Chair: Cristian Tiu, Committee Members: Feng Jiang and Dominik Roesch*

### **Untitled ESG related Difference-in-Difference Empirical Paper**

*Working Paper- Coauthors: George O. Aragon, Yuxiang Jiang, Juha Joenvaara, Cristian Tiu*

### **Untitled Job Quality Index Asset Pricing Paper**

*Working Paper- Coauthors: Cristian Tiu*

### **Information Asymmetry in IPO Prospectus Documents: Impact on Financial Analysts**

*Working Paper, Solo Author, Presented as Departmental Level Research Showcase as well as overall PhD Showcase*

### **ESG Impacts of with States and EPA, 2022**

*Pending Working Paper, with Jeayoung Park and Yi-Da Tsai*

---

\*Recipient of the first class of PhD Travel Grants for the European Financial Association this year in Barcelona

\*Recipient of the Excellence in Teaching Showcase Award at the University at Buffalo
