---
title: "Teaching"
editor: visual
---

# Teaching Experience

## University at Buffalo, Adjunct Professor

**MGF 637: Financial Modeling**

-   Fully designed Financial Modeling course using R/RStudio (Posit) built around 3 main themes: Data Science, Finance, and Advanced Modeling

-   Data Science: We start with basic data manipulation and transformation tools, then move on to basic data visualization techniques. Skills get honed as we peel back layers of the tidyverse and eventually entering SQL querying and API handling through a Tidy framework. Students learn Database Management as well as merging techniques.

-   Finance: Technical and Fundamental Analysis, starting with stock price data pulls, moving to computing returns and portfolio formation, to CAPM performance benchmarking and performance metrics at a technical level. We directly pull from an API to access key Financial Statements: Balance Sheet, Income Statement, Statement of Cashflows, and Key Fundamental Multiples/Ratios

-   Modeling: Advanced Time Series modeling through a Tidymodels framework. Topics include ARIMA Modeling, ETS Modeling (Exponential Smoothing), Prophet Modeling, as well as boosted models, random forest models, and students get to explore additional models found through the Parsnips engine design for Time Series Modeling (specifically using Federal Reserve Economic Variables via the FRED data source).

-   Advanced Data Querying through Wharton Research Data Services (WRDS). Students learn how to access CRSP for Stock Price Data, Compustat for key Accounting Data, as well as merge databases and establish a remote connection. We use this data source to build the Efficient Frontier and explore the Minimum Variance Framework, as well as Factor Modeling, Beta formation, Rolling Regressions, and Fama Macbeth Techniques.

**MGF 405: Advanced Corporate Finance**

-   Undergraduate Senior level course taught in-person, virtually, and through hybrid formats depending on the semester. Students are highly encouraged to participate and learn beyond simply the academic sense of material - from in-person discussion, forum boards, as well as Youtube/TikTok/additional learning techniques in the year 2023.

-   Course covers a review of Time Value of Money, including Perpetuities, Annuities, Bond Pricing, Future Value and Present Value calculations, and more. Additionally we move on to Capital Structure theory, from Cost of Equity to Cost of Debt and the Weighted Average Cost of Capital in terms of firm financing decisions.

-   Students learn not just how to compute via Financial Calculator and through Microsoft Excel, but course goes on to cover Power Query and Power Pivot framework for future student career opportunities. They also have the option to be exposed to either RStudio or Python as well for Extra Credit and additional skill building

**MGF 402: Investment Management**

-   Course structures on Asset Allocation, Portfolio Theory, Security Selection, Derivatives and more. Material forces students to explore the variety of asset classes to drive investment decisions beyond equities

-   Class incorporates applied knowledge of Excel Spreadsheets and the usage of Financial Calculators to complete pricing problems and properly prepare for potential CFA exam problems. This further reinforces materials beyond the theory presented in the textbook and slides

-   Modular approach to learning outcomes including opportunities with Python, R, and Power Query / Power Pivot

-   Students further had timely engagement thanks to the Cyptocurrency boom and post pandemic bubble in the equity markets - leading to exciting classroom discussions (Robinhood and wallstreetbets as well)

**MGE 302: Applied Economics**

-   Head TA and assisted in Applied Microeconomics course for the Business Administration majors here in the School of Management

-   Class incorporates 400 - 500 students per semester and incorporates Singapore Campus as well - providing a diverse domestic and international student pool

-   Beyond running weekly review sessions, exams are scheduled, office hours held, and a team of TA's is coordinated to ensure student engagement

-   Course covers common Microeconomics material - supply/demand curves and cost/revenue analysis

Additionally assisted with instructions of Fixed Income, Applied Statistics, and Portfolio Theory

# Buffalo State College (University)

## Adjunct Professor

**ECON 202: Microeconomics**

-   Classic Microeconomics course tailored for the undergraduate majors. Two sessions per semester including virtual, hybrid, and in-person instruction accordingly depending on semester offerings

-   Material includes supply/demand curves, marginal revenue vs marginal costs, organizational structure, consumer/producer surplus, cost sensitivity analysis

# Erie County Community College (ECC)

## Adjunct Professor

**ECO 181: Microeconomics**

-   Course tailored to both in-person and virtual environments for multiple sessions per semester - instruction including both Blackboard and Brightspace

-   Similar concepts as other Microeconomics course taught - supply/demand curves, marginal revenue vs marginal costs, organizational structure, consumer/producer surplus, cost sensitivity analysis

-   Methods of evaluation include flexibility to accommodate students work/extracurricular schedules - including Discussions to apply real world situations to course material

# Data Science Teaching Experience (R)

Through my Financial Modeling Course I have developed a strong interest in the Data Science community - specifically with RStats and accessible programming. This includes robust knowledge in Data Visualization and Data Manipulation techniques, specifically with the Tidyverse, ggplot2, tidymodels, and so much more. See below badge experience:
